--[[
Message Data for FTMOB
--]]

prefaces = {
"OK, but",
"Right, but how about this:",
"Not really, because",
"Alright, but",
"Hmm, good point, but to come back on that,",
"I'm not sure about that, because",
"Maybe, but I also think that",
"Just to play devil's advocate, what about this:",
"I'm not sure how that chimes with this, though:",
"I think we need to think about this, though:",
"We should consider that",
"I refute that entirely, since",
"You're taking that out of context, because",
"If that's the case then we'd have to concede that",
"We can't continue going down that route because",
"That reflects a common mis-reading disrupted by this:",
"OK, then it follows that",
"But I think even you would agree that",
"A more relevant point would concern the notion that",
"We can't allow that, since",
"The more contemporary take on these issues would be that",
"That's a total mis-step, which appears to deny that",
"But it's long been accepted that",
"I don't think that's fair at all;",
"I might be being overly provactive here, but",
"Now this might not be my position necessarily, but", 
"Some scholars argue that",
"If we accept this, we are led to also accept that",
"But I think everybody here would agree that",
"Let me propose that",
"Counter-proposal:",
"But your point is internally inconsistent, since",
"Let's be clear, what we're really talking about is that",
"There's something to be gained from arguing that",
"We are better placed if we begin with the proposition that",
"I think it's relevant to note that",
"I'm sure you'll think the point incredibly gauche, but",
"I feel like I have to remind you that",
"But that's completely irrelevant;",
"Can we start again from the point that",
"This takes us away from the point that",
"Let's stretch that point to it's limits, by considering that",
"It seems like you mean to say that",
"Perhaps, but then",
"Surely not! Remember,",
"The resolute reading of what you just said would be that",
"We are now down a rabbit hole, at the end of which is that",
"I want to break the deadlock by proposing that",
"OK, I'll bite; but",
"There's an elephant in the room though;",
"We're still circling around the point that"
}

statements = {
"the limits of my language mean the limits of my world.",
"whereof one cannot speak, thereof one must be silent.",
"the problems are solved, not by giving new information, but by arranging what we have known since long.",
"philosophy is a battle against the bewitchment of our intelligence by means of language.",
"when we can't think for ourselves, we can always quote.",
"if all possible scientific questions can be answered, the problems of life have still not been touched at all.",
"to imagine a language is to imagine a form of life.",
"what can be shown, cannot be said.",
"if a lion could speak, we could not understand him.",
"if we spoke a different language, we would perceive a somewhat different world.",
"all I know is what I have words for.",
"we learn by rearranging what we know.",
"what is thinkable is also possible.",
"to convince someone of the truth, it is not enough to state it, but rather one must find the path from error to truth.",
"the classifications made by philosophers and psychologists are like trying to classify clouds by their shape.",
"every explanation is after all an hypothesis.",
"one is unable to notice something because it is always before one's eyes.",
"to think that you are not following a rule is to follow a rule.",
"what cannot be imagined cannot even be talked about.",
"you learned the concept 'pain' when you learned language.",
"one can mistrust one's own senses, but not one's own belief.",
"what is your aim in philosophy? To show the fly the way out of the fly-bottle.",
"when you are philosophising you have to descend into primeval chaos and feel at home there.",
"for an answer which cannot be expressed, the question too cannot be expressed.",
"if a question can be put at all, then it can also be answered.",
"to understand a language means to be master of a technique.",
"an image is not a picture, but a picture can correspond to it.",
"if you tried to doubt everything you would not get as far as doubting anything.",
"everything that can be said, can be said clearly.",
"the world is made up of facts, not things.",
"every sign by itself seems dead. What gives it life? In use it is alive.",
"all mathematics is tautology.",
"the world is independent of my will.",
"the wish precedes the event; the will accompanies it.",
"what Copernicus really achieved was not the discovery of a true theory but of a fertile new point of view.",
"the world is everything that is the case.",
"most of the propositions and questions to be found in philosophical works are not false but nonsensical.",
"a picture is a model of reality.",
"it is clear that the causal nexus is not a nexus at all.",
"there are, indeed, things that cannot be put into words. They make themselves manifest. They are what is mystical.",
"belief in the causal nexus is superstition.",
"a mathematical proof must be perspicuous.",
"the world divides into facts.",
"our ordinary language has no means of describing a particular shade of colour.",
"the meaning of a word is its use in the language.",
"propositions show what they say: tautologies and contradictions show that they say nothing.",
"a wheel that can be turned though nothing else moves with it, is not a part of the mechanism.",
"we must do away with all explanation, and description alone must take its place.",
"one cannot guess how a word functions. One has to look at its use and learn from that.",
"if you use a trick in logic, whom can you be tricking other than yourself?",
"there is no criterion by which to recognise what is a colour, except that it is one of our colours.",
"an inner process stands in need of outward criteria.",
"a thought is a proposition with a sense.",
"what signs fail to express, their application shows. What signs slur over, their application says clearly.",
"when I obey a rule, I do not choose. I obey the rule blindly.",
"we just do not see how very specialised the use of \"I know\" is.",
"sometimes, in doing philospohy, one just wants to utter an inarticulate sound.",
"logic must look after itself. In a certain sense, we cannot make mistakes in logic.",
"logic takes care of itself; all we have to do is to look and see how it does it."
}
